name: Update gist
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Pip install"
        run: pip install -r requirements.txt

      - name: "Update gist"
        env:
          HOYO_UID: ${{ secrets.HOYO_UID }}
          HOYO_TOKEN: ${{ secrets.HOYO_TOKEN }}
          HOYO_TMID: ${{ secrets.HOYO_TMID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 36d06394bd89f9135b9a0f269212f5b5
        run: python main.py
